### ISSUE TITLE
games not showing up

### ISSUE THREAD

**Issue by chal8** [XenorPLxx/playnite-library-nintendo#3]
**Check for existing issue**
i am new-ish to github and the layout confuses me, but i tried to do a search for this error/bug an nothing turned up.

**Describe the bug**
owned nintendo switch games not showing up in playnite.
as far is i understand it, this plugin is based on this list https://ec.nintendo.com/my/transactions/1
i am able to get the plugin working - mostly - in playnite. a lot of my switch games show up, but not all of them, even though they are in the list above. the ones i've noticed are Assassin’s Creed Lineage, Assassin's Creed Revelations and Assassin's Creed Brotherhood, all bought on 01/07/2023 (european-style date). they show up in my switch library as 'the ezio collection' and not as individual games, though. not sure if that's relevant. 'the ezio collection' does not show up in playnite in any case.
 i've tried to update, but they're still not showing up. games bought at a later date are listed in playnite, however.

(also, there are other games that i own on the switch that are not in the list and therefore not in playnite. i assume it's because they were bought before 2021 and i further assume this is a known issue. i suppose i have to add them manually?)

**To Reproduce**
i have no idea. hopefully you don't have to buy these exact games/collection to test it out.

**Screenshots**
probably not necessary? will supply if asked.

**Diagnostics ID**
5878c947-a17a-4c81-9249-5b476198a827

**Comment by XenorPLxx** [comment]
Hi @chal8, sorry for the late response.

Can you go to the page, open up the developer tools in your browser and in the network tab look for a thing similar to the one on the screenshot? You might need to refresh the page for it to show up.
<img width="1471" alt="image" src="https://github.com/XenorPLxx/playnite-library-nintendo/assets/6712823/df5fe8bc-c289-48c4-b79e-3cb78ac23532">

I'm mostly interested in `content_type` and `device_type` fields, as we currently filter out only `title` for adding to Playnite and what you describe might be another thing, like a `package`.

We currently only take `title` and `bundle` into account:
```csharp
string[] nonGameContentTypes = { "consumable", "service", "aoc", "premium_ticket", "patch", "service_item" };
string[] gameContentTypes = { "title", "bundle" };
```

We also filter out only known devices:
```csharp
case "HAC":
  platform = "nintendo_switch";
  break;

case "CTR":
  platform = "nintendo_3ds";
  break;

case "WUP":
  platform = "nintendo_wiiu";
  break;
```

**Comment by chal8** [comment]
i'm sorry i'm a noob at this. the developers tools in firefox (windows) looks so different from your screenshot, i have no idea where to begin. i'm sure i can find what you're looking for but i'll need more details on where to look.
![Skjermbilde 2023-08-27 123639](https://github.com/XenorPLxx/playnite-library-nintendo/assets/12210214/bbe1ca78-2186-4465-ae15-7ba9f4e49037)
(hopefully no sensitive information is shown.. ?? if so, please tell me or delete the pic)

by the way, on https://www.nintendo.com/orders/ all my games shows up, including the ones ordered before 2021. so if it's possible to change from the previous source to this one, at least the old games would show up. obviously i don't know whether or not the 'packages' would.

**Comment by XenorPLxx** [comment]
Hi, the thing I'm looking for shoulb be in the Network tab:
![image](https://github.com/XenorPLxx/playnite-library-nintendo/assets/6712823/6f0c4388-57dc-455b-88cf-496cdf7b9c1a)

There'll be a list of requests and one of them should be for transactions, just like in my screenshot.

I wasn't aware of that second thing, I could work on adding it as a secondary source for games older than 2 years, as it doesn't have the same level of details:
![image](https://github.com/XenorPLxx/playnite-library-nintendo/assets/6712823/b001164d-45e7-4243-9327-103938cd8935)

From the list you've linked, it's impossible to recognize what's a game, bundle or another type of product, so all of them would show up in Playnite. It's also impossible to recognize what console those are for (this is a bit irrelevant since 3DS and Wii U stores are now closed, but might become relevant again for the next Nintendo console). It could work as an extra source, but I don't think switching for everything would be a good idea.

**Comment by chal8** [comment]
i thiiiink i got it?
![Skjermbilde 2023-08-27 200938](https://github.com/XenorPLxx/playnite-library-nintendo/assets/12210214/d2509c7b-03ee-40c9-978e-9b31d7090822)

is this the info you needed? it's games 2 to 5 that are not showing up


i reeally hoped the other link would work better, but if it doesn't then please disregard my suggestion ;)

**Comment by XenorPLxx** [comment]
https://github.com/XenorPLxx/playnite-library-nintendo/releases/tag/1.4 moves `aoc` `content_type` to be included in the games list. It'll also include DLCs for other games, but those can be just delete-ignored if not needed.
